### PR TITLE
Add delete functionality

### LINKED ISSUE #12: Deletion isn't implemented
There's currently no way to manually delete pastes, despite a 'delete button' in the view page.

PR incoming.

### PR DESCRIPTION
**Pull request by taigrr**
Closes #12

### CODE REVIEW

**Comment by taigrr** [comment]
Addresses issue #12

**Comment by prologic** [comment]
@taigrr I'm not sure which is the _correct_ changes here. Can you resolve the conflicts?

**Comment by taigrr** [comment]
@prologic  Done

**Comment by taigrr** [comment]
@prologic Done

**Pull request merged**
